### ISSUE TITLE
Fallback to bitmap font?

### ISSUE THREAD

**Issue by mittorn** [FWGS/mainui_cpp#15]
It would be good to add runtime fallback to bitmap font until release. User can do nothing if all ttf fonts does not exist in system

**Comment by a1batross** [comment]
It's a concern of platform-specific FindFontDataFile. I think font loading order should be:
1) Engine's COM_LoadFile in modification enabled builds.
2) FindFontDataFile.

Any modern OS have some TTF fonts which can be loaded by FindFontDataFile.

I don't see any real reasons for implementing bitmap font fallback in same builds, which uses TTF.

**Comment by mittorn** [comment]
What if there is no ttf at all? Just no files?
Bitmsp font us better than nothing

**Comment by a1batross** [comment]
Then mainui_cpp should be compiled with only bitmap support. Or bring external ttf fonts though extras.

**Comment by mittorn** [comment]
Why?

**Comment by a1batross** [comment]
Why DLL should be bigger with hardcoded data just because fallbacks? Broken system means broken system and nothing more. If platform does not have TTF files at all, I wonder how another software will work. 

Emscripten is a "special" platform, it's just even not OS. I think it may use or engine font renderer(pfnDrawCharacter), or provide external TTF font files.

**Comment by mittorn** [comment]
how much binary size takes this font? few kilobytes? Cut cyrillic part and size will be reduced twice. But we'll get working menu in case of font search code fail. Font search code is rely on many hardcoded values now (except windows)
Fallback font is just some heuristic, there no documentation that tells that droidsans should exist on every android.
We still need fallback system because sometimes not all ttf fonts present.
And you already have font manager. It is not too hard to create bitmap font class.

**Comment by mittorn** [comment]
32500 bytes including cyrillic part

**Comment by a1batross** [comment]
I will say it again. Broken means broken system.

Yes, Android font selector is pretty dumb and only really working way is just to bring your own TTF file.

Fontconfig will always return any fallback font file. And also it may be NOT ttf. Which is critical to stb backend. I also plan to remove stb backend, as stb can't work well on low-resolution due to missing hinting implementation and generally slower than freetype2. It's too hard to keep three(!) backend equal.

**Comment by mittorn** [comment]
menu will be larger than all other libraries both. Are you sure? And ft2 will not solve font search problems.
Also, placing own font in extras need open license font with all needed symbols. If we want to support languages not covered with cp1251/cp1252, it may be more than 2-3mb. Font manager does not support loading glyphs from multiple fonts to one font atlas for now.
Bold fonts looks good even without hinting and font atlas may be cached, so no reason to remove stb.
And it is so difficult to keep small 16kb fallback? It will not break anything, just prevent leaving menu without text at all. I have seen broken fonts in goldsrc many times in working system. Just no text in main menu.

**Comment by a1batross** [comment]
I didn't said that ft2 will solve our font searching problems. :) 
I said that it just renders better & faster than stb. It's the unavoidable future, when I will just don't want to maintain three backends at once. 

Yes, FontManager must support font amalgamation. In near future, when font rendering will be moved to engine in 0.20. 

It would be nice to have bitmap font class to avoid these ugly MAINUI_USE_CUSTOM_FONT_RENDER macros, which will break next day. It means less code(although may require some hacking into base font code) in comparison with macros. Only in this case bitmap fonts sounds good. But I totally don't want responsibility to maintain yet another font implementation, which may break too one day. These things can't be automated, it means that after any change in font rendering code I should re-run engine around 6 times to sure something didn't broke again.
